[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
user=root

[program:tcp_proxy]
command=socat TCP-LISTEN:5555,reuseaddr,fork TCP:127.0.0.1:6555
autostart=true
autorestart=true
stderr_logfile=/var/log/tcp_proxy_stderr.log
stdout_logfile=/var/log/tcp_proxy_stdout.log
priority=1

[program:ctf_server]
command=python3 /home/ctf/src/server.py --debug
directory=/home/ctf/src
autostart=true
autorestart=true
stderr_logfile=/var/log/ctf_server/stderr.log
stdout_logfile=/var/log/ctf_server/stdout.log
priority=2
user=ctf
environment=PYTHONDONTWRITEBYTECODE=1,PYTHONUNBUFFERED=1

[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface
